pipeline {
    agent any
    
    stages {
        stage('Cloning Git') {
            steps {
                git 'https://github.com/DeveloperWakeling/mocha_testing'
            }
        }
        stage('Install Dependencies'){
            steps {
                sh 'npm install'
            }
        }
        stage ('Test') {
            steps {
                sh 'npm test'
            }
        }
    }
}