pipeline {
    agent {
        docker {
            image 'node:14-alpine'
        }
    }
    
    stages {
        stage('Install Dependencies'){
            steps {
                sh 'cd source && npm install'
            }
        }
        stage ('Test') {
            steps {
                sh 'cd source && npm test'
            }
        }
    }
}